// Code generated by Kitex v0.5.1. DO NOT EDIT.
package payservice

import (
	server "github.com/cloudwego/kitex/server"
	pay "github.com/cqqqq777/go-kitex-mall/shared/kitex_gen/pay"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler pay.PayService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
