// Code generated by Kitex v0.5.1. DO NOT EDIT.
package opereteservice

import (
	server "github.com/cloudwego/kitex/server"
	operate "github.com/cqqqq777/go-kitex-mall/shared/kitex_gen/operate"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler operate.OpereteService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
